name: CI
on:
  push:
    branches-ignore:    
    - 'main'
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npm run tsc
      - run: npm run test
      - run: npm run build
